{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-ffmpeg",
    "version": "1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd"
          }
        },
        {
          "group": "io.github.abdallahmehiz",
          "module": "mpv-ffmpeg-android",
          "version": {
            "requires": "8.1.3-thor.29e619e767cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd.aar",
          "url": "media3-decoder-ffmpeg-1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd.aar",
          "size": 1718962,
          "sha512": "db51bc718cd1dd31d20385dfc45ec409bfd0d0197c0646e1a950dd7437560cb5c8a053e3f3993e93bcf0a8ab33509bd0b164667ed14b4d5fabff52cf805c3cff",
          "sha256": "6a89f64154aa93f1ab5c41aa9a921dd5d3f183536de64a2dd5d599f1722f36f2",
          "sha1": "ef643e497f0319ddf9fcb21d3bf6243d4b747dfa",
          "md5": "c1ad8a5bc50f9b78b6be877533d2e44f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd"
          }
        },
        {
          "group": "io.github.abdallahmehiz",
          "module": "mpv-ffmpeg-android",
          "version": {
            "requires": "8.1.3-thor.29e619e767cd"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd.aar",
          "url": "media3-decoder-ffmpeg-1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd.aar",
          "size": 1718962,
          "sha512": "db51bc718cd1dd31d20385dfc45ec409bfd0d0197c0646e1a950dd7437560cb5c8a053e3f3993e93bcf0a8ab33509bd0b164667ed14b4d5fabff52cf805c3cff",
          "sha256": "6a89f64154aa93f1ab5c41aa9a921dd5d3f183536de64a2dd5d599f1722f36f2",
          "sha1": "ef643e497f0319ddf9fcb21d3bf6243d4b747dfa",
          "md5": "c1ad8a5bc50f9b78b6be877533d2e44f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd-sources.jar",
          "url": "media3-decoder-ffmpeg-1.11.1-thor.2e2fc46d98ca-shared.29e619e767cd-sources.jar",
          "size": 16180,
          "sha512": "47ed50a806e3e06ed9e345789b660eb0d41b48e10a29759c9fa88d012c65c72ed89e25e12f0d8b725015b6dc31bb8cbbe5de9a5844ac121dda55164c261ce42d",
          "sha256": "da607d09209c932dbaaf2649c0d1490d35c57e343f4e9342d3ff6c0e73f9c57a",
          "sha1": "7c9e11b1dab631165e788c718712c59af6448fd6",
          "md5": "5029fa670c49882bd4e0579186d3ca72"
        }
      ]
    }
  ]
}
