{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.0.aar",
          "url": "media3-exoplayer-1.11.0.aar",
          "size": 1716177,
          "sha512": "04434cbad54366956ca6f18b66a2d4abdaf7e174c2c44e4f362a5b4631bf8a327d5d0367e457c823524127bb9f49951ac880356355596c5ba9a39d25e4fb9205",
          "sha256": "e62065d5ba91db20c68e0833bcc175df200fc4abaf1bd220e7c87a11437895b1",
          "sha1": "b952fb4a3f16b98f26cb9b3b31da5653f86e4488",
          "md5": "f43468594288767a7e7d8c783aee0abb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.0.aar",
          "url": "media3-exoplayer-1.11.0.aar",
          "size": 1716177,
          "sha512": "04434cbad54366956ca6f18b66a2d4abdaf7e174c2c44e4f362a5b4631bf8a327d5d0367e457c823524127bb9f49951ac880356355596c5ba9a39d25e4fb9205",
          "sha256": "e62065d5ba91db20c68e0833bcc175df200fc4abaf1bd220e7c87a11437895b1",
          "sha1": "b952fb4a3f16b98f26cb9b3b31da5653f86e4488",
          "md5": "f43468594288767a7e7d8c783aee0abb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.11.0-sources.jar",
          "url": "media3-exoplayer-1.11.0-sources.jar",
          "size": 1239525,
          "sha512": "d08122bcc1c3588623085562f385ef8697cbf765e2f7ed7c95e80ea48e7fc52e72784e373a5d90f547129008ca5b4f4a421e28940a67063a83b03f86dcd8108d",
          "sha256": "cba9576f5218c47efd052133df478139e3e768d68a1c93a7ca2ea71e8338d827",
          "sha1": "0c31b1de4661eb9f9e24565fefc05c664ac28800",
          "md5": "8f7a7b78de8f6c397917ef4acba25278"
        }
      ]
    }
  ]
}
