{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "url": "media3-datasource-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "size": 168586,
          "sha512": "3c3dfaf43dd21c30929d3330f67e6799b334188f01a134fda294bdad19235b1ee297cb7f4449c9d4b6ec6a48b23610f29ed234ecd7921827cd3511ac95fcfa3c",
          "sha256": "821be6f340fd6eaefe9a20dec26b9367ec8f3e10f7d348282e11f89c57b5188c",
          "sha1": "f6bec936c224b75d7854052e95f6e3ff604be5a0",
          "md5": "7cb21e2ab09f9038b332c248cfba0fc5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "url": "media3-datasource-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "size": 168586,
          "sha512": "3c3dfaf43dd21c30929d3330f67e6799b334188f01a134fda294bdad19235b1ee297cb7f4449c9d4b6ec6a48b23610f29ed234ecd7921827cd3511ac95fcfa3c",
          "sha256": "821be6f340fd6eaefe9a20dec26b9367ec8f3e10f7d348282e11f89c57b5188c",
          "sha1": "f6bec936c224b75d7854052e95f6e3ff604be5a0",
          "md5": "7cb21e2ab09f9038b332c248cfba0fc5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43-sources.jar",
          "url": "media3-datasource-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43-sources.jar",
          "size": 139089,
          "sha512": "7133fbea34a2520d2a98a532e8d7f82cdd0a2bda714a2a0504f1a8a787ea31dfece1b35b4d3369392518d5377bb3ea67e4615c499b582b8728ef712e534d1388",
          "sha256": "a54ddd9858ed2de57e07c5461dcebdae7a53d92a60210a2a3f5bf501398a5e4a",
          "sha1": "ee38b0a6b15ee2afb68099b9781a273188158e27",
          "md5": "6d2c78afb5fe3e8e7aee2d868da13c37"
        }
      ]
    }
  ]
}
