{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.0.aar",
          "url": "media3-ui-1.11.0.aar",
          "size": 338466,
          "sha512": "f0de3893e334c50f75773f637bb374e7e11dba9767efea7157d12f134b0ee424bfe5e38d0a9279772632a7979ec11c0a6cfb495b750ce9278b36b9aa79825456",
          "sha256": "823c81358f778ea31ee1661919930b73574863f3e8370c28577b19a006630219",
          "sha1": "53f4fd591c3deb868918112c5fec9ff133c5bffb",
          "md5": "3564027971e51bd444d41806032dfa52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.0.aar",
          "url": "media3-ui-1.11.0.aar",
          "size": 338466,
          "sha512": "f0de3893e334c50f75773f637bb374e7e11dba9767efea7157d12f134b0ee424bfe5e38d0a9279772632a7979ec11c0a6cfb495b750ce9278b36b9aa79825456",
          "sha256": "823c81358f778ea31ee1661919930b73574863f3e8370c28577b19a006630219",
          "sha1": "53f4fd591c3deb868918112c5fec9ff133c5bffb",
          "md5": "3564027971e51bd444d41806032dfa52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.11.0-sources.jar",
          "url": "media3-ui-1.11.0-sources.jar",
          "size": 121207,
          "sha512": "fb6bbfdcd28523f90012fd248e9d8b199d57992c580536cc374a3b3dcd667bfb40c3e3da64610d94377243c8e5378e5eace4b0830cf389bb40c0e7cee6dc3e19",
          "sha256": "2c915511644461f03226719062ae125ac7b29ddde9e96ae76d4364aa525f56fc",
          "sha1": "78544af0529d9f776248e375cecc5e72818ad1b3",
          "md5": "b10c7063726cbb9c651f7339f88d32f9"
        }
      ]
    }
  ]
}
