{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "url": "media3-common-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "size": 644505,
          "sha512": "1d43c44e7edff365e9f2f16eb1b013655e2e58a0712b7f43422e8ac91467564fda9e4e09006da9cceea59ab191ffb5336afe98142cbaf2023d1750a177364c72",
          "sha256": "b6a5f2016435a9522f788701cb8af2fdc5b5844ca475025bd015beea15ee2957",
          "sha1": "5052bdc9fa6d1c4d26e9f90c6dbe5972fb1436ed",
          "md5": "d77b37225a3eb89d66536e72830724f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-ktor",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-av1",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-ffmpeg",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-flac",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-iamf",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-mpegh",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-opus",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-vp9",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect-lottie",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-effect-ndk",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector-frame",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "url": "media3-common-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "size": 644505,
          "sha512": "1d43c44e7edff365e9f2f16eb1b013655e2e58a0712b7f43422e8ac91467564fda9e4e09006da9cceea59ab191ffb5336afe98142cbaf2023d1750a177364c72",
          "sha256": "b6a5f2016435a9522f788701cb8af2fdc5b5844ca475025bd015beea15ee2957",
          "sha1": "5052bdc9fa6d1c4d26e9f90c6dbe5972fb1436ed",
          "md5": "d77b37225a3eb89d66536e72830724f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf-sources.jar",
          "url": "media3-common-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf-sources.jar",
          "size": 526853,
          "sha512": "728011f4569fe07e40bdff93eac0caee7728548c77173f29da3f58c7180942c38e3976e7a1e8b659ba69d2d447d1811db2bdb35a083a4fdf9913b4ceadc4d224",
          "sha256": "c9a67ff8d485c9aeb77229a53ae91e39acdf9f591c9c8aff358307a4da031f21",
          "sha1": "87bdc869d5ef31cc37bf8f43815c47edd692b0ca",
          "md5": "1212681ed299021cf08a03b47db229d1"
        }
      ]
    }
  ]
}
