{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.0-thor.25d7606aa219-shared.7ba069f4f11d.aar",
          "url": "media3-exoplayer-1.11.0-thor.25d7606aa219-shared.7ba069f4f11d.aar",
          "size": 1703179,
          "sha512": "220586df34f89c986ba9c8895b5445a25fa8c4fc99d83df86dcb5a74be28099cc9a2008ba9edde1260432d80a92be6596c01a1c9f3f58078c9ee8e92bcc6443d",
          "sha256": "54c86e06697d0efd49bc5da3e95f5b87750f0d1e1f40877768da55a9ab3b8a7b",
          "sha1": "88705103fa840a63fd24fd5b08a9d07f30b43bde",
          "md5": "4405c49a3787fceb8a197d1440426be8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-thor.25d7606aa219-shared.7ba069f4f11d"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.0-thor.25d7606aa219-shared.7ba069f4f11d.aar",
          "url": "media3-exoplayer-1.11.0-thor.25d7606aa219-shared.7ba069f4f11d.aar",
          "size": 1703179,
          "sha512": "220586df34f89c986ba9c8895b5445a25fa8c4fc99d83df86dcb5a74be28099cc9a2008ba9edde1260432d80a92be6596c01a1c9f3f58078c9ee8e92bcc6443d",
          "sha256": "54c86e06697d0efd49bc5da3e95f5b87750f0d1e1f40877768da55a9ab3b8a7b",
          "sha1": "88705103fa840a63fd24fd5b08a9d07f30b43bde",
          "md5": "4405c49a3787fceb8a197d1440426be8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.11.0-thor.25d7606aa219-shared.7ba069f4f11d-sources.jar",
          "url": "media3-exoplayer-1.11.0-thor.25d7606aa219-shared.7ba069f4f11d-sources.jar",
          "size": 1229669,
          "sha512": "4d2e169d85042847f01d9f1db3b6e8e981ec43b47a03140a44541a6682aa52302274f31a6f38ebd9fa0fc9314b7e3444cb93d3f92feff5bce6c7c5fe8e678702",
          "sha256": "d7244d0f458fe3c64c97bccf269412d2e220c3a6b6d9d5cb6f09a89098e2069f",
          "sha1": "eb783724b4657e8d69a8ae6ccd2f524593399c6b",
          "md5": "ca50116a9abb7aa9044678b3138f6b8b"
        }
      ]
    }
  ]
}
