{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.0.aar",
          "url": "media3-datasource-1.11.0.aar",
          "size": 168586,
          "sha512": "de8908763705b30e71eed8ef0c3da7cec93025da1eb869c416ad90eea1de34cc07da8c5b4546841c5eec814612c2db36bf3dd63a43d4d6284c38e5b864f471e3",
          "sha256": "8d56fd1a4e50c666551a84ba67d7cccb01efcef9eed4dab055eddb5061365df2",
          "sha1": "c0df3e24de25096d3fcd7540e7cf042b4ca89dac",
          "md5": "4cd45b1ae5b22bce8700455be3ca82e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.0.aar",
          "url": "media3-datasource-1.11.0.aar",
          "size": 168586,
          "sha512": "de8908763705b30e71eed8ef0c3da7cec93025da1eb869c416ad90eea1de34cc07da8c5b4546841c5eec814612c2db36bf3dd63a43d4d6284c38e5b864f471e3",
          "sha256": "8d56fd1a4e50c666551a84ba67d7cccb01efcef9eed4dab055eddb5061365df2",
          "sha1": "c0df3e24de25096d3fcd7540e7cf042b4ca89dac",
          "md5": "4cd45b1ae5b22bce8700455be3ca82e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.11.0-sources.jar",
          "url": "media3-datasource-1.11.0-sources.jar",
          "size": 139089,
          "sha512": "7133fbea34a2520d2a98a532e8d7f82cdd0a2bda714a2a0504f1a8a787ea31dfece1b35b4d3369392518d5377bb3ea67e4615c499b582b8728ef712e534d1388",
          "sha256": "a54ddd9858ed2de57e07c5461dcebdae7a53d92a60210a2a3f5bf501398a5e4a",
          "sha1": "ee38b0a6b15ee2afb68099b9781a273188158e27",
          "md5": "6d2c78afb5fe3e8e7aee2d868da13c37"
        }
      ]
    }
  ]
}
