{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-effect",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.11.0.aar",
          "url": "media3-effect-1.11.0.aar",
          "size": 406779,
          "sha512": "cb394f9c553f418917674bb72221deac790b90fbe56d85adf3e4b5f28334a77a6e55abeb7cb6d05cab4664585164bdfd5cc1c465799155f3c0e80ef494090f01",
          "sha256": "76f572b8ed63068f32fcb6075a47e22524efccc6d3d0c8615ea7ab354feca24b",
          "sha1": "c9711c1816b0fd17d045cd1613a3a02ffadf7e0c",
          "md5": "ce789e8156ad495855baf733ab81c5fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.11.0.aar",
          "url": "media3-effect-1.11.0.aar",
          "size": 406779,
          "sha512": "cb394f9c553f418917674bb72221deac790b90fbe56d85adf3e4b5f28334a77a6e55abeb7cb6d05cab4664585164bdfd5cc1c465799155f3c0e80ef494090f01",
          "sha256": "76f572b8ed63068f32fcb6075a47e22524efccc6d3d0c8615ea7ab354feca24b",
          "sha1": "c9711c1816b0fd17d045cd1613a3a02ffadf7e0c",
          "md5": "ce789e8156ad495855baf733ab81c5fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-effect-1.11.0-sources.jar",
          "url": "media3-effect-1.11.0-sources.jar",
          "size": 258154,
          "sha512": "60ac10215f4bf8c84abc44ad009c20b347a69daa81a10345de7e1c6f2ea401dc1c32952e052bfe5ce3c5b498afa7ca708225c800ce2496319c157cf990261cd0",
          "sha256": "dcee8bc978d644808e38cc98bc4bc154629f80611ff628e491a7b70534182e59",
          "sha1": "22cc141830e53537a60b737bef7c5b19520a5f5e",
          "md5": "91bd3f603e491c769cbb94173dcfcb7b"
        }
      ]
    }
  ]
}
