{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 824613,
          "sha512": "7fd137c1ce0b72a849bfb07a95d33e01fa4d3bc521c737d8017cdc7e4396f08c3216573a296ac1aa72a77261701933900cba3424693f234b14aea053d35990b1",
          "sha256": "8bd152f6a1e943c4c7fffa389dd6744147f2f485eba573a69f9fc1a378693447",
          "sha1": "1d5cf8c258259f9091345c7c93b2b9a48b5ef24c",
          "md5": "cff71f4ded306cc41231aba09813cdb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 824613,
          "sha512": "7fd137c1ce0b72a849bfb07a95d33e01fa4d3bc521c737d8017cdc7e4396f08c3216573a296ac1aa72a77261701933900cba3424693f234b14aea053d35990b1",
          "sha256": "8bd152f6a1e943c4c7fffa389dd6744147f2f485eba573a69f9fc1a378693447",
          "sha1": "1d5cf8c258259f9091345c7c93b2b9a48b5ef24c",
          "md5": "cff71f4ded306cc41231aba09813cdb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.11.0-sources.jar",
          "url": "media3-extractor-1.11.0-sources.jar",
          "size": 706074,
          "sha512": "54ebab0273f4a6965565faffb9327c49246926e8a05c7cd5597a99030b67582c18de4c3da3d7183eff556cee8badca6d43d97f264eabe38a8c9e55d800341953",
          "sha256": "946a4bb4dbc62db3afe9d5dff54813f2b6616eb88b686c5e8c2ec83b809204a4",
          "sha1": "7c9a4c6346d66502d5a3556aba262f3dfd10bbd7",
          "md5": "0477b174808a2ab659ad7223e1b8cf12"
        }
      ]
    }
  ]
}
