{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-hls",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.11.0.aar",
          "url": "media3-exoplayer-hls-1.11.0.aar",
          "size": 259454,
          "sha512": "65d5159aa11ae37fc2f974a00d136d6deabf646099d7cd72a91835e2252d139e4069a0045c0d596b66aed7f8a456e4e950b643e5a8d140d1d2a78f6f8831a0e4",
          "sha256": "d38d6e936bb0833edc3357723b4883d32eee96b6b9e56e0e84760395c4b752a3",
          "sha1": "12759c4898f3123dbe33c597c7e136dc723da121",
          "md5": "53ab43ca25ecc317b14f674c47da8e6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.11.0.aar",
          "url": "media3-exoplayer-hls-1.11.0.aar",
          "size": 259454,
          "sha512": "65d5159aa11ae37fc2f974a00d136d6deabf646099d7cd72a91835e2252d139e4069a0045c0d596b66aed7f8a456e4e950b643e5a8d140d1d2a78f6f8831a0e4",
          "sha256": "d38d6e936bb0833edc3357723b4883d32eee96b6b9e56e0e84760395c4b752a3",
          "sha1": "12759c4898f3123dbe33c597c7e136dc723da121",
          "md5": "53ab43ca25ecc317b14f674c47da8e6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.11.0-sources.jar",
          "url": "media3-exoplayer-hls-1.11.0-sources.jar",
          "size": 171677,
          "sha512": "65fa5b20ecc446597b7f66f2f1ef0574f84945599ab24a79400ae7de97e1e8f56f1679afef5ed0d26836d6eff5fcfe3603660fd73aa14bc08370a43895304a67",
          "sha256": "15b4332f7d119e03136217a474f5b1c9f511f07a15a839d2ced8d6ea83755dca",
          "sha1": "ca2b9a8fa27c417a77ffb4d04cf07d938de99fee",
          "md5": "c97ed2eef1a42ea0753ec2898fd296c4"
        }
      ]
    }
  ]
}
