{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "url": "media3-ui-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "size": 338466,
          "sha512": "3c49b62eb9145478d65fe335ebc3641800c71bf82211db8da8be2bb7f4edd7ada42cbd7e66c51732b79f5ea359a60064f16072f2a78e9e4bda3d1aa597a1f6ee",
          "sha256": "40b67a90512fa159e4f2fa2dfb33baa9841062f65b4a44a6a9937a91e806b1d8",
          "sha1": "d76abe1f10b45ef5692bfe95a6707e07598de345",
          "md5": "eec2b7895c17a6a1c08f1554ef2ede47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-thor.284a04569fbd-shared.1a748fe2cd43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "url": "media3-ui-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43.aar",
          "size": 338466,
          "sha512": "3c49b62eb9145478d65fe335ebc3641800c71bf82211db8da8be2bb7f4edd7ada42cbd7e66c51732b79f5ea359a60064f16072f2a78e9e4bda3d1aa597a1f6ee",
          "sha256": "40b67a90512fa159e4f2fa2dfb33baa9841062f65b4a44a6a9937a91e806b1d8",
          "sha1": "d76abe1f10b45ef5692bfe95a6707e07598de345",
          "md5": "eec2b7895c17a6a1c08f1554ef2ede47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43-sources.jar",
          "url": "media3-ui-1.11.0-thor.284a04569fbd-shared.1a748fe2cd43-sources.jar",
          "size": 121207,
          "sha512": "fb6bbfdcd28523f90012fd248e9d8b199d57992c580536cc374a3b3dcd667bfb40c3e3da64610d94377243c8e5378e5eace4b0830cf389bb40c0e7cee6dc3e19",
          "sha256": "2c915511644461f03226719062ae125ac7b29ddde9e96ae76d4364aa525f56fc",
          "sha1": "78544af0529d9f776248e375cecc5e72818ad1b3",
          "md5": "b10c7063726cbb9c651f7339f88d32f9"
        }
      ]
    }
  ]
}
