{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "url": "media3-extractor-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "size": 826327,
          "sha512": "adbc9ddcee753dd3171618864e4c6846f1e66d854a3ae424d21bad011aa36b87e024682d84639a36195c5787610e13f1e039ca9ba5b3c47892c316a168681a8d",
          "sha256": "6c46f1eea5566906468feb666465d6a1d2caaee2af95d6d1df9df7b47ca9f751",
          "sha1": "ceebb2a48fa570b848e484bcc70d4ce3acf6d098",
          "md5": "2cf2b90b8c711fdf3d6548849e962e18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "url": "media3-extractor-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf.aar",
          "size": 826327,
          "sha512": "adbc9ddcee753dd3171618864e4c6846f1e66d854a3ae424d21bad011aa36b87e024682d84639a36195c5787610e13f1e039ca9ba5b3c47892c316a168681a8d",
          "sha256": "6c46f1eea5566906468feb666465d6a1d2caaee2af95d6d1df9df7b47ca9f751",
          "sha1": "ceebb2a48fa570b848e484bcc70d4ce3acf6d098",
          "md5": "2cf2b90b8c711fdf3d6548849e962e18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf-sources.jar",
          "url": "media3-extractor-1.11.1-thor.2e2fc46d98ca-shared.1005b294ffdf-sources.jar",
          "size": 707787,
          "sha512": "115a9f9f2bc6079b9f35183023ab5721fd38d1f4edf86de8fc470b006166f341533390204e5b5531b8ba8eb358ea1ff03ba77c0599ba33fa02ceca6048ea57ce",
          "sha256": "723ca4ed639e34bd8bd6ec352be0d36fcce3de6b778136949cfef876ae16035c",
          "sha1": "c72499c5534bac7b655b6699bf033263eb0ea324",
          "md5": "f8674f6878204fc082fabe79e4478807"
        }
      ]
    }
  ]
}
