{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource-okhttp",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0.aar",
          "url": "media3-datasource-okhttp-1.11.0.aar",
          "size": 9828,
          "sha512": "997614e18a5a0dfe89ab4eaadd44c653d5615a66d2e2c7f71f9106bd4edc2840d7f99c89f37c453470677f7bc6b83cff226828f332d71dcd49122b1e76cca396",
          "sha256": "754359d6738b8c1141b00fc74d1efa99bbcbd40d20447944e7fb94aafdbd9da2",
          "sha1": "f9a71a62d5c12b07de3020d145cf6f22cee97c0f",
          "md5": "fa659aec2e08bb3bf3f0a99676e76643"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0.aar",
          "url": "media3-datasource-okhttp-1.11.0.aar",
          "size": 9828,
          "sha512": "997614e18a5a0dfe89ab4eaadd44c653d5615a66d2e2c7f71f9106bd4edc2840d7f99c89f37c453470677f7bc6b83cff226828f332d71dcd49122b1e76cca396",
          "sha256": "754359d6738b8c1141b00fc74d1efa99bbcbd40d20447944e7fb94aafdbd9da2",
          "sha1": "f9a71a62d5c12b07de3020d145cf6f22cee97c0f",
          "md5": "fa659aec2e08bb3bf3f0a99676e76643"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0-sources.jar",
          "url": "media3-datasource-okhttp-1.11.0-sources.jar",
          "size": 6285,
          "sha512": "f7d8615b3f7a7cc9e0e3a11bd57142ec793a9e7175edccd569636b28f6fde826fd6beea7d69dba5bfc53473f2a8b2f85e1ce5df5c1a5e14079944d388b831a58",
          "sha256": "e90957224aa28b7602604a0a5543f36e81570ca952185a4ae5538aa430768cdc",
          "sha1": "57fe7ca60017aceb5ae2463ee519c267464cabae",
          "md5": "b79ac78703ae0b6fb52fdea35a18949f"
        }
      ]
    }
  ]
}
