{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-container",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.11.0.aar",
          "url": "media3-container-1.11.0.aar",
          "size": 67414,
          "sha512": "8aec263064704574c8231509b259e2c6ee717128094f2ed128d8e1d56d844862894e36c82db94bb848875050daf6c302fada05344dd0ddfc694d02949b52c663",
          "sha256": "ae5b1454ae3713d6260a621f36cc5f64ed80cd2c83c35f6c6c2c6efe1e308695",
          "sha1": "9893f1b72c8c0ad8bcf88dca6b4de9b60a61edd4",
          "md5": "03f99a0bf27c5503f27cfd060040611f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.11.0.aar",
          "url": "media3-container-1.11.0.aar",
          "size": 67414,
          "sha512": "8aec263064704574c8231509b259e2c6ee717128094f2ed128d8e1d56d844862894e36c82db94bb848875050daf6c302fada05344dd0ddfc694d02949b52c663",
          "sha256": "ae5b1454ae3713d6260a621f36cc5f64ed80cd2c83c35f6c6c2c6efe1e308695",
          "sha1": "9893f1b72c8c0ad8bcf88dca6b4de9b60a61edd4",
          "md5": "03f99a0bf27c5503f27cfd060040611f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-container-1.11.0-sources.jar",
          "url": "media3-container-1.11.0-sources.jar",
          "size": 55494,
          "sha512": "2ea38b712c0fb3b03cf1e578c4e01647805b39171b40ae2088b6aab45bec4ebffcee027c452abeb2ec42678dbb37ac2007ae643e74a7e3065f49bd83ee449f05",
          "sha256": "1389b973146391c7eb6cfb80d389cfb70f291a6fc092e1628af1886a6e00294c",
          "sha1": "3e37f3e1dd1f2998b51802e43fb962dfcb2baed3",
          "md5": "69d4b0f429e82ce10175949bbbccad6d"
        }
      ]
    }
  ]
}
